# Generated by Django 5.2rc1 on 2025-04-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('Администратор', 'Admin'), ('Старший официант', 'Senior_Waiter'), ('Официант', 'Waiter')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DishCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.compound')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='compounds',
            field=models.ManyToManyField(through='app_core.DishCompound', to='app_core.compound'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('is_served', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dishes', models.ManyToManyField(to='app_core.dish')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.check')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.order', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='orders',
            field=models.ManyToManyField(through='app_core.CheckOrder', to='app_core.order'),
        ),
    ]
